-- planner
CIRCLE_RADIUS = 4.0;
STOP_DIST = 0.7;
SEARCH_BUFFER = 5;
CLEARANCE = 0.3;
HEURISTIC_INFLATION = 1.05;

-- scoring function
W_CLEARANCE = 0.15;
W_GOAL_DIST = 3.0;
MAX_LOCAL_GOAL_DIST = CIRCLE_RADIUS;
